# Usa una imagen base de Python liviana
FROM python:3.11-slim

# 1. Instalar FFmpeg dentro de la imagen
# Usamos -y para confirmar y borramos la caché de apt para que la imagen pese menos
RUN apt-get update && apt-get install -y \
    ffmpeg \
    && rm -rf /var/lib/apt/lists/*

# 2. Establecer el directorio de trabajo
WORKDIR /app

# 3. Copiar e instalar dependencias de Python
COPY Requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# 4. Copiar tu código
COPY . .

# 5. Comando para ejecutar tu herramienta
CMD ["python", "src"]