from typing import Protocol
from feature_interfaces.enums.settings_enum import ConfigEnum


class ConfigServiceProtocol(Protocol):
    def get_config_value(self, service_name: ConfigEnum) -> str: ...

class LoggerProtocol(Protocol):
    def debug(self, message: str) -> None: ...
    def info(self, message: str) -> None: ...
    def warning(self, message: str) -> None: ...
    def error(self, message: str) -> None: ...
    def critical(self, message: str) -> None: ...